### ISSUE TITLE
PHP8/Acorn - Declaration of, Should be compatible with

### ISSUE THREAD

**Issue by imcodingideas** [Log1x/pagi#16]
I'm having issues installing this in a the latest sage theme. I'm getting this error: 

```
Fatal error: Declaration of Illuminate\Foundation\Application::storagePath() must be compatible with Illuminate\Contracts\Foundation\Application::storagePath($path = '') in .../vendor/roots/acorn/src/Illuminate/Foundation/Application.php on line 458
```

**Comment by Log1x** [comment]
Not experiencing this on any of my sites but it's possible you need to:

```sh
$ composer remove roots/acorn log1x/pagi
$ composer require roots/acorn
$ composer require log1x/pagi
```

that way Acorn v3 is installed initially with ^9.0 illuminate dependencies so Pagi uses the ^9.0 dependency version for `illuminate/pagination`.

If this doesn't seem to work in all environments, I'll consider a v1.1 release for Acorn v3+ but I'm hoping that isn't necessary.

Also make sure your Composer dependencies were all installed with the same PHP version (in WordPress-land this would generally be 8.0.x).
