### ISSUE TITLE
v1.0.9 publicPath() fatal error

### ISSUE THREAD

**Issue by mike-sheppard** [Log1x/pagi#21]
hey 👋 @Log1x  no rush on this, just a heads up that the latest release is throwing an error. It could def. be something on my side so will keep digging around early next week. 

- bedrock composer: `"roots/acorn": "3.2.0"`
- theme composer: `"log1x/pagi": "1.0.9"` (`1.0.8` works perfectly 👌)

```
Fatal error: Declaration of Illuminate\Foundation\Application::publicPath() 
must be compatible with Illuminate\Contracts\Foundation\Application::publicPath($path = '') 
in [site_root]/site/vendor/roots/acorn/src/Illuminate/Foundation/Application.php 
on line 453
```

**Comment by Log1x** [comment]
You'll have to move `log1x/pagi` to Bedrock, otherwise Composer doesn't know better and it will install Illuminate 10.x dependencies when your Acorn is still using 9.x.

**Comment by mike-sheppard** [comment]
perfecto! thanks for the super quick response, much appreciated! 🙏
