### ISSUE TITLE
Pagi not working inside of AJAX call

### ISSUE THREAD

**Issue by rjanits** [Log1x/pagi#22]
Hi Brandon 👋
I'm experiencing an issue where the `Pagi` package does not return the expected pagination when used inside an AJAX call. The pagination works perfectly fine when rendering normally on page load, but when I attempt to use `Pagi` within an AJAX response, the pagination object returns empty or incorrect data.

**Steps to Reproduce:**
- Set up a `WP_Query` instance within an AJAX callback in WordPress.
- Use Pagi to generate pagination based on the query.
- Return the pagination HTML as part of the AJAX response.
- Observe that the data.pagination of the AJAX response is empty or does not render correctly.

```
<?php

/**
 * Ajax functions
 */

namespace App;

use WP_Query;
use Log1x\Pagi\PagiFacade as Pagi;

add_action('wp_ajax_my_ajax_posts', __NAMESPACE__ . '\\ajax_filter_pagination');
add_action('wp_ajax_nopriv_my_ajax_posts', __NAMESPACE__ . '\\ajax_filter_pagination');

function ajax_filter_pagination()
{
    // prepare our arguments for the query
    $args = json_decode(stripslashes($_POST['query']), true);

    // update a page number
    $args['paged'] = isset($_POST['page']) ? intval($_POST['page']) : 1;
    $args['cat'] = isset($_POST['category_id']) ? intval($_POST['category_id']) : '';

    // Get the sorting option
    $sort_order = isset($_POST['sort_order']) ? sanitize_text_field($_POST['sort_order']) : 'newest';

    // Check for tag filter
    if (isset($_POST['post_tag']) && !empty($_POST['post_tag'])) {
        $args['tag'] = sanitize_text_field($_POST['post_tag']);
    }

    // Adjust sorting based on the selected option
    if ($sort_order === 'shortest_reading_time') {
        $args['meta_key'] = 'reading_time';
        $args['orderby'] = 'meta_value_num';
        $args['order'] = 'ASC';
    } else {
        $args['orderby'] = 'date';
        $args['order'] = 'DESC';
    }

    // Make sure we only get published posts
    $args['post_status'] = 'publish';

    $posts_html = '';

    // Create a new WP_Query instance instead of using query_posts()
    $query = new WP_Query($args);

    if ($query->have_posts()) {
        ob_start(); // start buffering because we do not need to print the posts now

        while ($query->have_posts()) {
            $query->the_post();

            echo '<div class="post-grid__column">';
            echo \Roots\view('partials.card');
            echo '</div>';
        }

        $posts_html = ob_get_clean(); // we pass the posts into a variable
    } else {
        $posts_html = '<p>'.__('Keine Beiträge gefunden.').'</p>';
    }

    // Check if there are multiple pages for pagination
    $pagination_html = '';
    if ($query->max_num_pages > 1) {
        // Build pagination with Pagi
        $pagination = Pagi::build(['query' => $query]);

        // If Pagi returns an empty object, debug it
        if (empty($pagination)) {
            error_log('Pagi returned an empty object.');
        } else {
            $pagination_html = $pagination->links('components.pagination');
        }
    }

    // Reset post data
    wp_reset_postdata();

    echo json_encode([
        'posts' => $posts_html,
        'pagination' => $pagination_html,
        'query' => json_encode($query->query_vars),
    ]);

    wp_die();
}

```

As a temporary workaround, I am currently using `paginate_links()` to generate pagination links, and this works as expected. However, I would like to understand why `Pagi` does not correctly output the pagination in the AJAX response. Any insights or suggestions on why this might be happening and how to properly use `Pagi` in this context would be greatly appreciated.

Thank you for your time and all your contributions!

Edit: Does not work with `WP_Query` as first assumed.

**Comment by Log1x** [comment]
try `Pagi::setQuery($query)->build()`

**Comment by rjanits** [comment]
> try `Pagi::setQuery($query)->build()`

This returns the following message: `Call to a member function build() on null`

It seems that `WP_Query` is not compatible with Pagi after all - As first assumed. Can you confirm this? 
For archive pages, everything works fine on normal pageload.

**Comment by Log1x** [comment]
Do `->setQuery()` and `->build()` on separate lines.

Take a look at the original PR: https://github.com/Log1x/pagi/pull/10

Sorry, I hadn't personally used it before - I just knew that it existed and `build()` didn't otherwise accept any arguments.
