### ISSUE TITLE
How to Offset WordPress Queries with correct pagination

### ISSUE THREAD

**Issue by huubl** [Log1x/pagi#3]
Hi,

I use a different number of posts (8) on the first post archive page, the rest of the paged pages use the default 'posts_per_page' which I set on 9 posts. I use [this code ](https://gist.github.com/smeedijzer-internet/1651344888900534ab0c1ac809633d44), which works with the default pagination. 

But with Pagi, the pagination is not correct. Any idea why and how to fix it?

Edit:
I cant figure out how to fix it, but found: https://stackoverflow.com/a/49954493/12992342

**Comment by huubl** [comment]
Hi, it's a while ago. Any hints on how to do this?

**Comment by Log1x** [comment]
Really sorry for the delay on this....

Did you figure out a solution? I haven't given this package the attention it deserves. 😞
