### ISSUE TITLE
Does not work on term archives

### ISSUE THREAD

**Issue by codepuncher** [Log1x/pagi#4]
This works great on the posts archive/home/blog.
However, when using Pagi on a term archive, it doesn't see any other pages to display.

Using `{!! paginate_links() !!}` works fine and as expected on here.

What information might be needed to help debug this?

Sage 10
Pagi 1.0.2

Thanks

**Comment by Log1x** [comment]
hmm I'm not 100% sure why it wouldn't work on terms.

I'd manually edit and try dumping some of the stuff [here](https://github.com/Log1x/pagi/blob/master/src/Pagi.php#L52-L75) to see if you can spot why it wouldn't be
